travis:
  secure:
    BINSTAR_TOKEN: KnizG8huxMJv1w/B4UvQJPO8VKdDd1mWvvssbGQlsjE11nOAXaGRbeMUka9hyBuK2QIj/oVs2K3ef7AX0ZvSFVC6CamlmS4bTD6oMUfJozBXYERaVjr+A3h3yLcJTGmpGiiPCXzZ7gUFGUx9906LO9SGDovfHXf7GdfH6g3Epid4G6w8NzDf8ROiQphS+Geq0x3m2zKWlPgbuHmAUEo8aqUzQ4jgeSMetiaHxInmj8cINgBx+9Rd0LO7WZDiBpB/0YjIm+ZJIV5b07MKDQkcMH16aZUmii+8lqCdVLRPzNmAcf2MOltyK7/eLY89GjXl7gYI6NtgCHH/lotiaFT9SWTry7HnHqikHc2U3i6joKeNtn5hpUvuS2qS9gT8aFhcDOCUBk3YU5IUyAymwV7vNY2EtecWYa7ipPZjpZsObCyr3My94C+CeGp0QRvqzwRGEC+VwmOlv9ZHR/aFarl2aLPOb7KoG3TWb5PDJom524ly7xGQ+UKDWE+nP5tpiGMEEndCLMtQEah6kdrWrg7dQqfxhSemFJ3OsT2vpnmJflN0rDT15v6hMhxPpT0gXOZiHTJssFlyBiutNdqVti6Gs+yIS30l2ca8x8j/NvDi/zfdtXO4AaAIZcRqA4BZ592lSQp+SEG+0FVOxLGK8GOPQ7JbK538Er+5DLqUYOROONQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
